export interface Organization {
  id: string
  name: string
  type: string
  location: string
  address: string
  phone: string
  email: string
  website: string
  description: string
  services: string[]
  hours: string
  verified: boolean
  latitude?: number
  longitude?: number
}

export const organizations: Organization[] = [
  // Addis Ababa - Private Psychology / Counseling Centers
  {
    id: '1',
    name: 'Kal Psychological Services',
    type: 'Private Psychology Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '090 486 0086',
    email: 'Kal@kal.et',
    website: '',
    description: 'Private psychological services and counseling in Addis Ababa.',
    services: ['Individual Therapy', 'Counseling', 'Psychological Assessment'],
    hours: 'Mon-Fri: 9:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '2',
    name: 'Fitret Counseling',
    type: 'Counseling Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '091 548 4852',
    email: 'Endegana@FitretCounseling.com',
    website: '',
    description: 'Counseling services providing emotional and mental support.',
    services: ['Counseling', 'Family Therapy', 'Personal Development'],
    hours: 'Mon-Fri: 9:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '3',
    name: 'Melkam Psychological Services',
    type: 'Private Psychology Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '097 860 0038',
    email: 'melkamtherapy@gmail.com',
    website: '',
    description: 'Professional psychological services and therapy.',
    services: ['Psychotherapy', 'Individual Counseling', 'Mental Health Support'],
    hours: 'Mon-Fri: 9:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '4',
    name: 'Aha Psychological Services Plc',
    type: 'Private Psychology Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '011 662 2437',
    email: 'info@ahaethiopia.com',
    website: 'www.ahaethiopia.com',
    description: 'Comprehensive psychological services and mental health support.',
    services: ['Psychological Counseling', 'Assessment', 'Therapy', 'Corporate Wellness'],
    hours: 'Mon-Fri: 9:00 AM - 6:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  // Addis Ababa - Psychiatric Centers & Specialized Clinics
  {
    id: '5',
    name: 'Sitota Center for Mental Health Care',
    type: 'Psychiatric Clinic',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '8187',
    email: 'sitota.psych.info@gmail.com',
    website: '',
    description: 'Specialized mental health care and psychiatric services.',
    services: ['Psychiatric Care', 'Mental Health Treatment', 'Crisis Support'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '6',
    name: 'Gize Psychiatry Center',
    type: 'Psychiatric Clinic',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '098 668 9565',
    email: 'gizepsychiatrycenter@gmail.com',
    website: 'gizepsychiatrycenter.com',
    description: 'Professional psychiatric care and treatment services.',
    services: ['Psychiatric Evaluation', 'Medication Management', 'Mental Health Treatment'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '7',
    name: 'Lebeza Psychiatry Clinic',
    type: 'Psychiatric Clinic',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '096 611 1111',
    email: 'editorethiopia@gmail.com',
    website: '',
    description: 'Specialized psychiatric clinic offering comprehensive mental health services.',
    services: ['Psychiatric Services', 'Mental Health Counseling', 'Treatment'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '8',
    name: 'Asheten Psychiatry & Rehabilitation Specialized Center',
    type: 'Psychiatric Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '095 340 4142',
    email: 'ashetenpsychatry@gmail.com',
    website: '',
    description: 'Specialized psychiatric and rehabilitation services.',
    services: ['Psychiatric Care', 'Rehabilitation', 'Mental Health Treatment', 'Recovery Support'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '9',
    name: 'Abbichu Memorial Psychiatric Specialty and Rehab Center',
    type: 'Psychiatric Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '094 176 7676',
    email: '',
    website: '',
    description: 'Memorial psychiatric specialty and rehabilitation center.',
    services: ['Psychiatric Specialty Care', 'Rehabilitation', 'Mental Health Support'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '10',
    name: 'Dr Ginbaru Psychiatry Center',
    type: 'Psychiatric Clinic',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '+251 930 03 29 98',
    email: 'tg.dr.ginbaru.clinic@gmail.com',
    website: '',
    description: 'Professional psychiatric clinic led by experienced psychiatrist.',
    services: ['Psychiatric Evaluation', 'Mental Health Treatment', 'Medication Management'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '11',
    name: 'El Star Psychiatry Specialty Center',
    type: 'Psychiatric Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '011 618 7035',
    email: 'editorethiopia@gmail.com',
    website: '',
    description: 'Specialty psychiatric center offering comprehensive mental health services.',
    services: ['Psychiatric Services', 'Mental Health Treatment', 'Counseling'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  // Addis Ababa - Hospitals with Mental Health Services
  {
    id: '12',
    name: 'Eka Kotebe Hospital & Neuroscience Institute',
    type: 'Hospital',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '+251 116 680 897',
    email: 'cherinetbedada12@gmail.com',
    website: '',
    description: 'Major hospital with neuroscience and mental health services.',
    services: ['Mental Health Services', 'Psychiatric Care', 'Neuroscience Services', 'Emergency Psychiatry'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '13',
    name: 'ALERT Hospital',
    type: 'Hospital',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '+251 113 47 16 32',
    email: 'contact@alerthospital.gov.et',
    website: '',
    description: 'Government hospital providing comprehensive mental health services.',
    services: ['Psychiatric Care', 'Mental Health Services', 'Emergency Care', 'Inpatient Treatment'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '14',
    name: 'Premier Hospital Mental Health Clinic',
    type: 'Hospital',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '+254-717-999-000',
    email: 'info@premierhospital.org',
    website: '',
    description: 'Premier hospital with specialized mental health clinic.',
    services: ['Mental Health Clinic', 'Psychiatric Services', 'Counseling', 'Mental Health Treatment'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  // Addis Ababa - Other Known Clinics
  {
    id: '15',
    name: 'Abrihot Specialized Psychological Center',
    type: 'Psychological Center',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '098 973 7372',
    email: 'info@abrihot.com',
    website: 'www.abrihot.com',
    description: 'Specialized psychological services and mental health support.',
    services: ['Psychological Counseling', 'Assessment', 'Individual Therapy', 'Family Counseling'],
    hours: 'Mon-Fri: 9:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  {
    id: '16',
    name: 'Dr. Dawit Health Services',
    type: 'Psychiatric Clinic',
    location: 'Addis Ababa',
    address: 'Addis Ababa, Ethiopia',
    phone: '+251 948 272 829',
    email: 'drdawitassefa@gmail.com',
    website: '',
    description: 'Professional psychiatric clinic providing mental health services.',
    services: ['Psychiatric Services', 'Mental Health Treatment', 'Counseling'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.0320,
    longitude: 38.7469
  },
  // Other Ethiopian Cities - Hospitals & Medical Centers
  {
    id: '17',
    name: 'Jimma University Medical Center',
    type: 'Hospital',
    location: 'Jimma',
    address: 'Jimma, Ethiopia',
    phone: '+251 47 111 2200',
    email: 'info@jmc.edu.et',
    website: '',
    description: 'University medical center with mental health services.',
    services: ['Mental Health Services', 'Psychiatric Care', 'Medical Treatment', 'Education'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 7.6795,
    longitude: 36.8368
  },
  {
    id: '18',
    name: 'Hawassa University Comprehensive Specialized Hospital',
    type: 'Hospital',
    location: 'Hawassa',
    address: 'Hawassa, Ethiopia',
    phone: '+251 46 220 1511',
    email: 'info@hu.edu.et',
    website: '',
    description: 'Comprehensive hospital providing specialized mental health services.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Emergency Services', 'Inpatient Treatment'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 5.0280,
    longitude: 38.4922
  },
  {
    id: '19',
    name: 'Ayder Comprehensive Specialized Hospital',
    type: 'Hospital',
    location: 'Mekelle',
    address: 'Mekelle, Ethiopia',
    phone: '+251 34 441 6688',
    email: 'info@mu.edu.et',
    website: '',
    description: 'Comprehensive specialized hospital with psychiatric services.',
    services: ['Psychiatric Care', 'Mental Health Services', 'Specialized Treatment', 'Emergency Care'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 13.4995,
    longitude: 39.4708
  },
  {
    id: '20',
    name: 'Felege Hiwot Comprehensive Specialized Hospital',
    type: 'Hospital',
    location: 'Bahir Dar',
    address: 'Bahir Dar, Ethiopia',
    phone: '+251 58 220 0410',
    email: 'info@fhcs.edu.et',
    website: '',
    description: 'Comprehensive hospital serving northern Ethiopia with mental health services.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Emergency Services', 'Community Health'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 11.6065,
    longitude: 37.3942
  },
  {
    id: '21',
    name: 'University of Gondar Comprehensive Specialized Hospital',
    type: 'Hospital',
    location: 'Gondar',
    address: 'Gondar, Ethiopia',
    phone: '+251 58 114 1232',
    email: 'info@uog.edu.et',
    website: '',
    description: 'University hospital providing comprehensive mental health services.',
    services: ['Psychiatric Care', 'Mental Health Services', 'Medical Treatment', 'Education'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 12.6050,
    longitude: 37.4669
  },
  {
    id: '22',
    name: 'Dilchora Referral Hospital',
    type: 'Hospital',
    location: 'Dire Dawa',
    address: 'Dire Dawa, Ethiopia',
    phone: '+251 25 111 0080',
    email: 'info@dilchorahospital.et',
    website: '',
    description: 'Referral hospital with mental health and psychiatric services.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Emergency Services', 'Referral Care'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 9.5439,
    longitude: 41.8687
  },
  {
    id: '23',
    name: 'Adama Hospital Medical College',
    type: 'Hospital',
    location: 'Adama',
    address: 'Adama (Nazret), Ethiopia',
    phone: '+251 22 211 0016',
    email: 'info@ahmc.edu.et',
    website: '',
    description: 'Medical college hospital offering mental health services.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Medical Education', 'Emergency Care'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 8.5428,
    longitude: 39.2689
  },
  {
    id: '24',
    name: 'Dessie Referral Hospital',
    type: 'Hospital',
    location: 'Dessie',
    address: 'Dessie, Ethiopia',
    phone: '+251 33 311 2200',
    email: 'info@dessiehospital.et',
    website: '',
    description: 'Referral hospital providing mental health services for northeast Ethiopia.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Emergency Services', 'Community Health'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 11.1298,
    longitude: 39.6350
  },
  {
    id: '25',
    name: 'Jijiga University Referral Hospital',
    type: 'Hospital',
    location: 'Jijiga',
    address: 'Jijiga, Ethiopia',
    phone: '+251 25 775 0300',
    email: 'info@jju.edu.et',
    website: '',
    description: 'University referral hospital with psychiatric services.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Emergency Services', 'Educational Training'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 9.3500,
    longitude: 42.7833
  },
  {
    id: '26',
    name: 'Hiwot Fana Specialized University Hospital',
    type: 'Hospital',
    location: 'Harar',
    address: 'Harar, Ethiopia',
    phone: '+251 25 666 2211',
    email: 'info@hu.edu.et',
    website: '',
    description: 'Specialized university hospital providing mental health services.',
    services: ['Psychiatric Care', 'Mental Health Services', 'Specialized Treatment', 'Medical Education'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 9.3103,
    longitude: 42.1213
  },
  // Additional organizations from Jimma
  {
    id: '27',
    name: 'Jimma University Psychology Department Clinic',
    type: 'Psychology Clinic',
    location: 'Jimma',
    address: 'Jimma, Ethiopia',
    phone: '+251 47 111 4455',
    email: 'psychology@ju.edu.et',
    website: '',
    description: 'University psychology department providing clinical services.',
    services: ['Psychological Counseling', 'Assessment', 'Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 7.6795,
    longitude: 36.8368
  },
  {
    id: '28',
    name: 'Jimma University Counseling & Guidance Center',
    type: 'Counseling Center',
    location: 'Jimma',
    address: 'Jimma, Ethiopia',
    phone: '+251 47 111 8899',
    email: 'counseling@ju.edu.et',
    website: '',
    description: 'University counseling and guidance services for students and community.',
    services: ['Counseling', 'Guidance', 'Student Support', 'Community Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 7.6795,
    longitude: 36.8368
  },
  // Additional organizations from Hawassa
  {
    id: '29',
    name: 'Hawassa University Hospital Psychiatry Unit',
    type: 'Psychiatric Clinic',
    location: 'Hawassa',
    address: 'Hawassa, Ethiopia',
    phone: '+251 46 220 1511',
    email: 'info@hu.edu.et',
    website: '',
    description: 'Specialized psychiatry unit providing psychiatric care.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Emergency Services'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 5.0280,
    longitude: 38.4922
  },
  {
    id: '30',
    name: 'Hawassa University Psychology & Counseling Unit',
    type: 'Counseling Center',
    location: 'Hawassa',
    address: 'Hawassa, Ethiopia',
    phone: '+251 46 221 7788',
    email: 'counseling@hu.edu.et',
    website: '',
    description: 'Psychology and counseling services for students and community.',
    services: ['Psychological Counseling', 'Assessment', 'Counseling', 'Support Groups'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 5.0280,
    longitude: 38.4922
  },
  {
    id: '31',
    name: 'Hawassa University Student Counseling Center',
    type: 'Counseling Center',
    location: 'Hawassa',
    address: 'Hawassa, Ethiopia',
    phone: '+251 46 221 9900',
    email: 'studenthelp@hu.edu.et',
    website: '',
    description: 'Student-focused counseling and support services.',
    services: ['Student Counseling', 'Mental Health Support', 'Crisis Support'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 5.0280,
    longitude: 38.4922
  },
  // Additional organizations from Mekelle
  {
    id: '32',
    name: 'Mekelle University Psychology Department Clinic',
    type: 'Psychology Clinic',
    location: 'Mekelle',
    address: 'Mekelle, Ethiopia',
    phone: '+251 34 441 2233',
    email: 'psychology@mu.edu.et',
    website: '',
    description: 'University psychology department clinical services.',
    services: ['Psychological Counseling', 'Assessment', 'Individual Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 13.4995,
    longitude: 39.4708
  },
  {
    id: '33',
    name: 'Mekelle University Counseling Center',
    type: 'Counseling Center',
    location: 'Mekelle',
    address: 'Mekelle, Ethiopia',
    phone: '+251 34 442 8899',
    email: 'counseling@mu.edu.et',
    website: '',
    description: 'University counseling services for students and community.',
    services: ['Counseling', 'Mental Health Support', 'Student Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 13.4995,
    longitude: 39.4708
  },
  // Additional organizations from Bahir Dar
  {
    id: '34',
    name: 'Bahir Dar University Psychology Clinic',
    type: 'Psychology Clinic',
    location: 'Bahir Dar',
    address: 'Bahir Dar, Ethiopia',
    phone: '+251 58 220 5566',
    email: 'psychology@bdu.edu.et',
    website: '',
    description: 'Psychology clinic providing clinical psychological services.',
    services: ['Psychological Counseling', 'Assessment', 'Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 11.6065,
    longitude: 37.3942
  },
  {
    id: '35',
    name: 'Bahir Dar University Student Counseling Center',
    type: 'Counseling Center',
    location: 'Bahir Dar',
    address: 'Bahir Dar, Ethiopia',
    phone: '+251 58 221 8899',
    email: 'counseling@bdu.edu.et',
    website: '',
    description: 'Student counseling and mental health support services.',
    services: ['Student Counseling', 'Mental Health Support', 'Crisis Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 11.6065,
    longitude: 37.3942
  },
  // Additional organizations from Gondar
  {
    id: '36',
    name: 'University of Gondar Psychology Clinic',
    type: 'Psychology Clinic',
    location: 'Gondar',
    address: 'Gondar, Ethiopia',
    phone: '+251 58 114 5566',
    email: 'psychology@uog.edu.et',
    website: '',
    description: 'University psychology clinic providing clinical services.',
    services: ['Psychological Counseling', 'Assessment', 'Individual Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 12.6050,
    longitude: 37.4669
  },
  {
    id: '37',
    name: 'University of Gondar Counseling Center',
    type: 'Counseling Center',
    location: 'Gondar',
    address: 'Gondar, Ethiopia',
    phone: '+251 58 115 8899',
    email: 'counseling@uog.edu.et',
    website: '',
    description: 'University counseling center for students and community.',
    services: ['Counseling', 'Mental Health Support', 'Student Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 12.6050,
    longitude: 37.4669
  },
  // Additional organizations from Dire Dawa
  {
    id: '38',
    name: 'Dire Dawa University Psychology Unit',
    type: 'Psychology Clinic',
    location: 'Dire Dawa',
    address: 'Dire Dawa, Ethiopia',
    phone: '+251 25 112 7788',
    email: 'psychology@ddu.edu.et',
    website: '',
    description: 'University psychology unit providing psychological services.',
    services: ['Psychological Counseling', 'Assessment', 'Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.5439,
    longitude: 41.8687
  },
  {
    id: '39',
    name: 'Dire Dawa University Counseling Center',
    type: 'Counseling Center',
    location: 'Dire Dawa',
    address: 'Dire Dawa, Ethiopia',
    phone: '+251 25 112 9900',
    email: 'counseling@ddu.edu.et',
    website: '',
    description: 'University counseling services.',
    services: ['Counseling', 'Mental Health Support', 'Student Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.5439,
    longitude: 41.8687
  },
  // Additional organizations from Adama
  {
    id: '40',
    name: 'Adama University Psychology Department Clinic',
    type: 'Psychology Clinic',
    location: 'Adama',
    address: 'Adama, Ethiopia',
    phone: '+251 22 211 7788',
    email: 'psychology@aau.edu.et',
    website: '',
    description: 'University psychology department clinical services.',
    services: ['Psychological Counseling', 'Assessment', 'Individual Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 8.5428,
    longitude: 39.2689
  },
  {
    id: '41',
    name: 'Adama University Counseling Center',
    type: 'Counseling Center',
    location: 'Adama',
    address: 'Adama, Ethiopia',
    phone: '+251 22 212 8899',
    email: 'counseling@aau.edu.et',
    website: '',
    description: 'University counseling center for students and community.',
    services: ['Counseling', 'Mental Health Support', 'Student Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 8.5428,
    longitude: 39.2689
  },
  // Additional organizations from Dessie
  {
    id: '42',
    name: 'Wollo University Psychology Clinic',
    type: 'Psychology Clinic',
    location: 'Dessie',
    address: 'Dessie, Ethiopia',
    phone: '+251 33 312 7788',
    email: 'psychology@wu.edu.et',
    website: '',
    description: 'University psychology clinic providing psychological services.',
    services: ['Psychological Counseling', 'Assessment', 'Individual Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 11.1298,
    longitude: 39.6350
  },
  {
    id: '43',
    name: 'Wollo University Counseling Center',
    type: 'Counseling Center',
    location: 'Dessie',
    address: 'Dessie, Ethiopia',
    phone: '+251 33 312 9900',
    email: 'counseling@wu.edu.et',
    website: '',
    description: 'University counseling services for students and community.',
    services: ['Counseling', 'Mental Health Support', 'Student Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 11.1298,
    longitude: 39.6350
  },
  // Additional organizations from Jijiga
  {
    id: '44',
    name: 'Karamara General Hospital Psychiatry Services',
    type: 'Hospital',
    location: 'Jijiga',
    address: 'Jijiga, Ethiopia',
    phone: '+251 25 775 4455',
    email: 'info@karamara.et',
    website: '',
    description: 'General hospital providing psychiatric services.',
    services: ['Psychiatric Services', 'Mental Health Care', 'Emergency Psychiatry'],
    hours: 'Mon-Sun: 24/7',
    verified: true,
    latitude: 9.3500,
    longitude: 42.7833
  },
  {
    id: '45',
    name: 'Jigjiga University Psychology Unit',
    type: 'Psychology Clinic',
    location: 'Jijiga',
    address: 'Jijiga, Ethiopia',
    phone: '+251 25 775 6677',
    email: 'psychology@ju.edu.et',
    website: '',
    description: 'University psychology unit providing psychological services.',
    services: ['Psychological Counseling', 'Assessment', 'Individual Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.3500,
    longitude: 42.7833
  },
  {
    id: '46',
    name: 'Jigjiga University Counseling Center',
    type: 'Counseling Center',
    location: 'Jijiga',
    address: 'Jijiga, Ethiopia',
    phone: '+251 25 775 8899',
    email: 'counseling@ju.edu.et',
    website: '',
    description: 'University counseling services for students and community.',
    services: ['Counseling', 'Mental Health Support', 'Student Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.3500,
    longitude: 42.7833
  },
  // Additional organizations from Harar
  {
    id: '47',
    name: 'Harar Health Sciences College Psychology Clinic',
    type: 'Psychology Clinic',
    location: 'Harar',
    address: 'Harar, Ethiopia',
    phone: '+251 25 666 7788',
    email: 'psychology@harar.edu.et',
    website: '',
    description: 'Health sciences college psychology clinic.',
    services: ['Psychological Counseling', 'Assessment', 'Individual Therapy'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.3103,
    longitude: 42.1213
  },
  {
    id: '48',
    name: 'Harar University Counseling Center',
    type: 'Counseling Center',
    location: 'Harar',
    address: 'Harar, Ethiopia',
    phone: '+251 25 667 9900',
    email: 'counseling@harar.edu.et',
    website: '',
    description: 'University counseling services for students and community.',
    services: ['Counseling', 'Mental Health Support', 'Student Services'],
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
    verified: true,
    latitude: 9.3103,
    longitude: 42.1213
  },
]

export function getOrganizationById(id: string): Organization | undefined {
  return organizations.find(org => org.id === id)
}

export function searchOrganizations(query: string): Organization[] {
  const lowerQuery = query.toLowerCase()
  return organizations.filter(org =>
    org.name.toLowerCase().includes(lowerQuery) ||
    org.type.toLowerCase().includes(lowerQuery) ||
    org.location.toLowerCase().includes(lowerQuery) ||
    org.description.toLowerCase().includes(lowerQuery) ||
    org.services.some(s => s.toLowerCase().includes(lowerQuery))
  )
}

export function filterByType(type: string): Organization[] {
  return organizations.filter(org => org.type === type)
}

export function filterByLocation(location: string): Organization[] {
  return organizations.filter(org => org.location === location)
}

export function filterByService(service: string): Organization[] {
  return organizations.filter(org => org.services.includes(service))
}

export function getAvailableLocations(): string[] {
  return [...new Set(organizations.map(org => org.location))]
}

export function getOrganizationTypes(): string[] {
  return [...new Set(organizations.map(org => org.type))]
}
